# Generated by Django 5.2.7 on 2025-11-14 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_brokercompliance_outreach_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='databrokers2025',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('primary_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('onboarding_notes', models.TextField(blank=True)),
                ('default_request_type', models.CharField(choices=[('delete', 'Delete / Remove'), ('do_not_sell', 'Do Not Sell / Share'), ('do_not_contact', 'Do Not Contact')], default='delete', max_length=32)),
                ('weekly_status_opt_in', models.BooleanField(default=True)),
                ('last_status_email_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConsumerBrokerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('contacted', 'Contacted'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('bounced', 'Bounced'), ('no_response', 'No Response')], db_index=True, default='queued', max_length=20)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_type', models.CharField(choices=[('delete', 'Delete / Remove'), ('do_not_sell', 'Do Not Sell / Share'), ('do_not_contact', 'Do Not Contact')], default='delete', max_length=20)),
                ('batch_number', models.PositiveIntegerField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_response_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('broker_contact_name', models.CharField(blank=True, max_length=255)),
                ('broker_contact_email', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('last_email_subject', models.CharField(blank=True, max_length=255)),
                ('last_email_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumer_statuses', to='website.databrokers2025')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_statuses', to='website.consumer')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField()),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='website.databrokers2025')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='website.consumer')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='website.consumerbrokerstatus')),
            ],
            options={
                'ordering': ('-sent_at',),
            },
        ),
        migrations.CreateModel(
            name='EmailDripState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_index', models.PositiveIntegerField(default=0)),
                ('last_batch_size', models.PositiveIntegerField(default=0)),
                ('total_contacted', models.PositiveIntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drip_state', to='website.consumer')),
            ],
        ),
        migrations.AddIndex(
            model_name='consumerbrokerstatus',
            index=models.Index(fields=['consumer', 'status'], name='website_con_consume_2d9784_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerbrokerstatus',
            index=models.Index(fields=['broker', 'status'], name='website_con_broker__49066f_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerbrokerstatus',
            index=models.Index(fields=['status', 'request_type'], name='website_con_status_ad4f5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='consumerbrokerstatus',
            unique_together={('consumer', 'broker')},
        ),
    ]
