# Generated by Django 5.2.7 on 2025-11-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_databrokers2025_is_active_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donotcallrequest',
            name='weekly_status_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donotemailrequest',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='donotemailrequest',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='donotemailrequest',
            name='weekly_status_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
