# Generated by Django 5.2.7 on 2025-11-19 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_donotcallrequest_weekly_status_opt_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donotcallrequest',
            name='phone',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(message='Enter a 10-digit phone number with digits only.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='donotemailrequest',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10-digit phone number with digits only.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='donotemailrequest',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Enter a 10-digit phone number with digits only.', regex='^\\d{10}$')]),
        ),
    ]
