# Generated by Django 5.2.7 on 2026-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_servicemarket_shopify_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicemarket',
            new_name='website_ser_slug_st_215ecd_idx',
            old_name='website_ser_slug_st_e32676_idx',
        ),
        migrations.RenameIndex(
            model_name='servicemarket',
            new_name='website_ser_state_i_70897f_idx',
            old_name='website_ser_state_i_ae5d34_idx',
        ),
        migrations.AlterField(
            model_name='brokeracknowledgement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicemarket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
