# Generated by Django 5.2.7 on 2026-08-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_website_ser_slug_st_e32676_idx_website_ser_slug_st_215ecd_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier referenced in code/templates, e.g. 'services-shopify-showcase-1'.", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, help_text='Internal label — not shown on the site.', max_length=200)),
                ('image', models.ImageField(upload_to='site_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text shown on the page.', max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
            },
        ),
    ]
