# Generated by Django 5.2.7 on 2026-06-25 05:04

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Insight = apps.get_model("insights", "Insight")
    seen = set()
    for insight in Insight.objects.order_by("created_at"):
        base = slugify(insight.title) or f"insight-{insight.pk}"
        slug = base
        n = 1
        while slug in seen:
            slug = f"{base}-{n}"
            n += 1
        seen.add(slug)
        insight.slug = slug
        insight.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='author',
            field=models.CharField(blank=True, default='SwanTech', max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='Override the canonical URL. Leave blank to use the page URL.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='featured_image_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insight',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Full URL to the featured/hero image.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='json_ld_extra',
            field=models.JSONField(blank=True, help_text='Extra JSON-LD properties merged into the Article schema. Must be a valid JSON object, e.g. {"speakable": {"@type": "SpeakableSpecification"}}.', null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='noindex',
            field=models.BooleanField(default=False, help_text='Add noindex, nofollow robots meta tag to prevent search engine indexing.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='og_description',
            field=models.CharField(blank=True, help_text='Open Graph description. Defaults to the SEO description.', max_length=300),
        ),
        migrations.AddField(
            model_name='insight',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph image URL. Defaults to the featured image.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social sharing. Defaults to the SEO title.', max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='reading_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Estimated reading time in minutes. Leave blank to auto-calculate from section word count.', null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Meta description shown in search results. Defaults to the excerpt. Keep under 160 chars.', max_length=160),
        ),
        migrations.AddField(
            model_name='insight',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords.', max_length=255),
        ),
        migrations.AddField(
            model_name='insight',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Page &lt;title&gt; tag. Defaults to the post title if blank. Keep under 60 chars.', max_length=70),
        ),
        # Add slug as nullable/non-unique first so existing rows don't clash.
        migrations.AddField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
        # Populate unique slugs for all existing rows.
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Now apply the unique constraint.
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, max_length=280, unique=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='insight',
            name='twitter_description',
            field=models.CharField(blank=True, help_text='Twitter card description. Defaults to OG description.', max_length=300),
        ),
        migrations.AddField(
            model_name='insight',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title. Defaults to OG title.', max_length=100),
        ),
        migrations.AddField(
            model_name='insight',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='description',
            field=models.TextField(help_text='Short excerpt shown on the listing page and used as the default meta description.'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='topic',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('web-development', 'Web Development'), ('ios-development', 'iOS Development'), ('ecommerce', 'eCommerce'), ('data-privacy', 'Data Privacy')], max_length=32),
        ),
        migrations.CreateModel(
            name='InsightSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('heading_level', models.CharField(choices=[('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], default='h2', max_length=2)),
                ('content', models.TextField(blank=True, help_text='Paragraph text for this section. Basic HTML is supported.')),
                ('image_url', models.URLField(blank=True, help_text='Optional image to display in this section.')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('image_caption', models.CharField(blank=True, max_length=255)),
                ('link_text', models.CharField(blank=True, help_text='Call-to-action link label.', max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('link_open_new_tab', models.BooleanField(default=False)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='insights.insight')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
