# Generated by Django 5.2.7 on 2026-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_insight_author_insight_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='featured_image_url',
        ),
        migrations.RemoveField(
            model_name='insightsection',
            name='image_url',
        ),
        migrations.AddField(
            model_name='insight',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload the featured/hero image.', upload_to='insights/featured/'),
        ),
        migrations.AddField(
            model_name='insightsection',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this section.', upload_to='insights/sections/'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='og_image_url',
            field=models.URLField(blank=True, help_text='Open Graph image URL (external link). Leave blank to use the featured image.'),
        ),
    ]
