# Generated by Django 5.2.7 on 2026-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_remove_insight_featured_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
