# Generated by Django 5.2.7 on 2026-08-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_alter_insight_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='body_markdown',
            field=models.TextField(blank=True, help_text='Raw markdown from VibeSEO. Auto-rendered into the first content section on every save.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='List of {question, answer} dicts from VibeSEO.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='focus_keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='insight',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='List of {text, url} dicts from VibeSEO, rendered as a Related links block.'),
        ),
        migrations.AddField(
            model_name='insight',
            name='seo_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='vibeseo_post_id',
            field=models.IntegerField(blank=True, db_index=True, help_text="VibeSEO's internal post ID. Set automatically by the webhook; blank for manually authored insights.", null=True, unique=True),
        ),
        migrations.AddField(
            model_name='insight',
            name='vibeseo_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='topic',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('web-development', 'Web Development'), ('ios-development', 'iOS Development'), ('ecommerce', 'eCommerce'), ('data-privacy', 'Data Privacy'), ('general', 'General')], max_length=32),
        ),
    ]
