# Generated by Django 5.2.7 on 2026-08-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_insight_body_markdown_insight_faq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='body_markdown',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='focus_keyword',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='internal_links',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='seo_score',
        ),
        migrations.AddField(
            model_name='insight',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Hotlinked hero image URL (e.g. from VibeSEO). Used only if no image is uploaded above.'),
        ),
        migrations.AlterField(
            model_name='insight',
            name='vibeseo_post_id',
            field=models.IntegerField(blank=True, db_index=True, help_text="VibeSEO's stable post ID. Set automatically by the sync command; blank for manually authored insights.", null=True, unique=True),
        ),
    ]
